- name: Remove existing containers
  block:
    - name: Stop app
      docker_compose:
        project_src: "/opt/composes/{{ docker_image }}"
        state: absent

    - name: delete image
      docker_image:
        name: "{{ docker_image }}"
        state: absent

    - name:  Remove compose directory
      ansible.builtin.file:
        path: "/opt/composes/{{ docker_image }}"
        state: absent
  tags:
    - wipe
  when: web_app_full_wipe | bool
