apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app
  labels:
    app: python-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-web-app
  template:
    metadata:
      labels:
        app: python-web-app
    spec:
      containers:
      - name: python-app
        image: rentacat45/python-web-app:latest
        stdin: true
        ports:
          - containerPort: 8000
            name: app-python-port
